name: Deploy MultiDocker
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t faisalch10/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true faisalch10/react-test npm run test

      - run: docker build -t faisalch10/multi-client ./client
      - run: docker build -t faisalch10/multi-nginx ./nginx
      - run: docker build -t faisalch10/multi-server ./server
      - run: docker build -t faisalch10/multi-worker ./worker

      - run: docker push faisalch10/multi-client
      - run: docker push faisalch10/multi-nginx
      - run: docker push faisalch10/multi-server
      - run: docker push faisalch10/multi-worker
